"""
Batch map script for assignment part 3.

This script uses an ArcGIS Pro project template (.aprx) and exports one map
for each Beijing district/county. It clips a population raster by each district
boundary and displays:
    - clipped population raster
    - district boundary
    - township centroid points belonging to that district

Recommended script tool parameters:
0 District polygon layer, e.g. E:\\bjmap\\区县.shp
1 District name field, e.g. NAME
2 Township centroid point layer generated by 02_create_centroid_points.py
3 Population raster generated by 03_spline_interpolation.py
4 Output map folder
5 Optional ArcGIS Pro project template (.aprx). If omitted, the script uses
  the current ArcGIS Pro project and its first map/layout.
"""

from __future__ import annotations

import os
import re

import arcpy
from arcpy.sa import ExtractByMask


SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
DEFAULT_TEMPLATE = os.path.join(SCRIPT_DIR, "beijing_population_map_template.aprx")


def safe_name(text):
    return re.sub(r'[\\/:*?"<>|]+', "_", str(text).strip())


def sql_eq(dataset, field, value):
    field_expr = arcpy.AddFieldDelimiters(dataset, field)
    value_expr = str(value).replace("'", "''")
    return "{} = '{}'".format(field_expr, value_expr)


def clear_layers(map_obj):
    for layer in list(map_obj.listLayers()):
        map_obj.removeLayer(layer)


def make_district_population_maps(
    district_fc,
    district_name_field,
    centroid_points,
    population_raster,
    out_folder,
    template_aprx=DEFAULT_TEMPLATE,
):
    os.makedirs(out_folder, exist_ok=True)
    arcpy.env.overwriteOutput = True
    arcpy.CheckOutExtension("Spatial")

    if template_aprx and os.path.exists(template_aprx):
        aprx = arcpy.mp.ArcGISProject(template_aprx)
    else:
        arcpy.AddWarning(
            "No valid APRX template was provided. Using the current ArcGIS Pro project."
        )
        aprx = arcpy.mp.ArcGISProject("CURRENT")

    maps = aprx.listMaps()
    layouts = aprx.listLayouts()
    if not maps or not layouts:
        raise arcpy.ExecuteError(
            "The project must contain at least one map and one layout with a map frame."
        )
    map_obj = maps[0]
    layout = layouts[0]
    map_frames = layout.listElements("MAPFRAME_ELEMENT")
    if not map_frames:
        raise arcpy.ExecuteError("The selected layout must contain a map frame.")
    map_frame = map_frames[0]

    districts = []
    with arcpy.da.SearchCursor(district_fc, [district_name_field]) as cursor:
        for (name,) in cursor:
            districts.append(name)

    temp_gdb = arcpy.management.CreateFileGDB(out_folder, "temp_clip.gdb").getOutput(0)

    for district_name in districts:
        clean = safe_name(district_name)
        where = sql_eq(district_fc, district_name_field, district_name)
        district_layer = "district_lyr"
        point_layer = "centroid_lyr"
        arcpy.management.MakeFeatureLayer(district_fc, district_layer, where)
        arcpy.management.MakeFeatureLayer(
            centroid_points,
            point_layer,
            "DISTRICT = '{}'".format(str(district_name).replace("'", "''")),
        )

        clip_raster = os.path.join(temp_gdb, "pop_{}".format(clean[:20]))
        ExtractByMask(population_raster, district_layer).save(clip_raster)

        clear_layers(map_obj)
        raster_layer = map_obj.addDataFromPath(clip_raster)
        boundary_layer = map_obj.addDataFromPath(district_layer)
        center_layer = map_obj.addDataFromPath(point_layer)

        raster_layer.name = "{}人口分布".format(district_name)
        boundary_layer.name = "{}行政区边界".format(district_name)
        center_layer.name = "{}质心点".format(district_name)

        map_frame.camera.setExtent(arcpy.Describe(district_layer).extent)
        map_frame.camera.scale *= 1.08

        for elem in layout.listElements("TEXT_ELEMENT"):
            if elem.name == "Title":
                elem.text = "{}人口分布图".format(district_name)

        out_png = os.path.join(out_folder, "{}_人口分布图.png".format(clean))
        layout.exportToPNG(out_png, resolution=300)
        arcpy.AddMessage("Exported {}".format(out_png))

    arcpy.CheckInExtension("Spatial")


def main():
    district_fc = arcpy.GetParameterAsText(0)
    district_name_field = arcpy.GetParameterAsText(1) or "NAME"
    centroid_points = arcpy.GetParameterAsText(2)
    population_raster = arcpy.GetParameterAsText(3)
    out_folder = arcpy.GetParameterAsText(4) or os.path.join(SCRIPT_DIR, "district_maps")
    template_aprx = arcpy.GetParameterAsText(5) or ""
    make_district_population_maps(
        district_fc,
        district_name_field,
        centroid_points,
        population_raster,
        out_folder,
        template_aprx,
    )


if __name__ == "__main__":
    main()
